-- Sylo Schema - Smart Farming Platform

DROP TABLE IF EXISTS automation_actions;
DROP TABLE IF EXISTS alerts;
DROP TABLE IF EXISTS satellite_observations;
DROP TABLE IF EXISTS iot_readings;
DROP TABLE IF EXISTS iot_devices;
DROP TABLE IF EXISTS field_crops;
DROP TABLE IF EXISTS decision_rules;
DROP TABLE IF EXISTS crop_types;
DROP TABLE IF EXISTS fields;
DROP TABLE IF EXISTS farm_users;
DROP TABLE IF EXISTS farms;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE farms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description CLOB,
    city VARCHAR(100),
    state VARCHAR(50),
    latitude DECIMAL(10,7),
    longitude DECIMAL(10,7),
    created_at TIMESTAMP
);

CREATE TABLE farm_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(30) NOT NULL,
    created_at TIMESTAMP,
    CONSTRAINT fk_farm_users_farm FOREIGN KEY (farm_id) REFERENCES farms(id),
    CONSTRAINT fk_farm_users_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_farm_users UNIQUE (farm_id, user_id)
);

CREATE TABLE fields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    area_hectares DECIMAL(10,2),
    latitude DECIMAL(10,7),
    longitude DECIMAL(10,7),
    status VARCHAR(20),
    created_at TIMESTAMP,
    CONSTRAINT fk_fields_farm FOREIGN KEY (farm_id) REFERENCES farms(id)
);

CREATE TABLE crop_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description CLOB,
    ideal_min_soil_moisture DECIMAL(5,2),
    ideal_max_soil_moisture DECIMAL(5,2),
    ideal_min_temperature DECIMAL(5,2),
    ideal_max_temperature DECIMAL(5,2),
    ideal_min_ndvi DECIMAL(5,2),
    ideal_max_ndvi DECIMAL(5,2),
    created_at TIMESTAMP
);

CREATE TABLE decision_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_type_id BIGINT NOT NULL,
    rule_name VARCHAR(100) NOT NULL,
    condition_description CLOB,
    alert_type VARCHAR(50),
    severity VARCHAR(20),
    active BOOLEAN,
    created_at TIMESTAMP,
    CONSTRAINT fk_decision_rules_crop_type FOREIGN KEY (crop_type_id) REFERENCES crop_types(id)
);

CREATE TABLE field_crops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id BIGINT NOT NULL,
    crop_type_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    expected_end_date DATE,
    end_date DATE,
    status VARCHAR(20),
    created_at TIMESTAMP,
    CONSTRAINT fk_field_crops_field FOREIGN KEY (field_id) REFERENCES fields(id),
    CONSTRAINT fk_field_crops_crop_type FOREIGN KEY (crop_type_id) REFERENCES crop_types(id)
);

CREATE TABLE iot_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    device_type VARCHAR(50) NOT NULL,
    serial_number VARCHAR(100),
    status VARCHAR(20),
    latitude DECIMAL(10,7),
    longitude DECIMAL(10,7),
    created_at TIMESTAMP,
    CONSTRAINT fk_iot_devices_field FOREIGN KEY (field_id) REFERENCES fields(id)
);

CREATE TABLE iot_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iot_device_id BIGINT NOT NULL,
    reading_type VARCHAR(50) NOT NULL,
    "value" DECIMAL(10,2) NOT NULL,
    unit VARCHAR(20),
    read_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP,
    CONSTRAINT fk_iot_readings_device FOREIGN KEY (iot_device_id) REFERENCES iot_devices(id)
);

CREATE TABLE satellite_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id BIGINT NOT NULL,
    source VARCHAR(50),
    ndvi DECIMAL(5,2),
    surface_temperature DECIMAL(5,2),
    soil_moisture_index DECIMAL(5,2),
    cloud_coverage DECIMAL(5,2),
    observed_at TIMESTAMP,
    created_at TIMESTAMP,
    CONSTRAINT fk_satellite_observations_field FOREIGN KEY (field_id) REFERENCES fields(id)
);

CREATE TABLE alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id BIGINT NOT NULL,
    field_crop_id BIGINT,
    alert_type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    message CLOB,
    status VARCHAR(20),
    created_at TIMESTAMP,
    resolved_at TIMESTAMP,
    CONSTRAINT fk_alerts_field FOREIGN KEY (field_id) REFERENCES fields(id),
    CONSTRAINT fk_alerts_field_crop FOREIGN KEY (field_crop_id) REFERENCES field_crops(id)
);

CREATE TABLE automation_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id BIGINT NOT NULL,
    iot_device_id BIGINT,
    alert_id BIGINT,
    action_type VARCHAR(50) NOT NULL,
    status VARCHAR(20),
    duration_minutes INTEGER,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    created_at TIMESTAMP,
    CONSTRAINT fk_automation_actions_field FOREIGN KEY (field_id) REFERENCES fields(id),
    CONSTRAINT fk_automation_actions_iot_device FOREIGN KEY (iot_device_id) REFERENCES iot_devices(id),
    CONSTRAINT fk_automation_actions_alert FOREIGN KEY (alert_id) REFERENCES alerts(id)
);

-- Indexes
CREATE INDEX idx_farm_users_farm_id ON farm_users(farm_id);
CREATE INDEX idx_farm_users_user_id ON farm_users(user_id);
CREATE INDEX idx_fields_farm_id ON fields(farm_id);
CREATE INDEX idx_field_crops_field_id ON field_crops(field_id);
CREATE INDEX idx_field_crops_crop_type_id ON field_crops(crop_type_id);
CREATE INDEX idx_iot_devices_field_id ON iot_devices(field_id);
CREATE INDEX idx_iot_readings_device_id ON iot_readings(iot_device_id);
CREATE INDEX idx_iot_readings_read_at ON iot_readings(read_at);
CREATE INDEX idx_satellite_observations_field_id ON satellite_observations(field_id);
CREATE INDEX idx_satellite_observations_observed_at ON satellite_observations(observed_at);
CREATE INDEX idx_alerts_field_id ON alerts(field_id);
CREATE INDEX idx_alerts_status ON alerts(status);
CREATE INDEX idx_automation_actions_alert_id ON automation_actions(alert_id);
